Repository algorithm-archivists/algorithm-archive, pull requests merged in 2018-09, with the labels that each got.

#345 Implement Java version of the stable marriage problem.
  contents/stable_marriage_problem/code/java/stable-marriage.java
  contents/stable_marriage_problem/stable_marriage_problem.md
Labels: Implementation

#360 Implement bogo in ruby
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/ruby/bogo.rb
Labels: Implementation

#361 Implement monte carlo in ruby
  contents/monte_carlo_integration/code/ruby/monte_carlo.rb
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation

#339 Added Tree traversal in Crystal-lang
  CONTRIBUTORS.md
  contents/tree_traversal/code/crystal/tree-traversal.cr
  contents/tree_traversal/tree_traversal.md
Labels: Implementation

#366 Euclidean julia edit
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Small Changes

#371 Updating Monte Carlo in Java
  contents/monte_carlo_integration/code/java/MonteCarlo.java
Labels: Implementation Edit

#290 Implementation Edit to Verlet Integration in Java
  contents/verlet_integration/code/java/Verlet.java
  contents/verlet_integration/code/java/verlet.java
  contents/verlet_integration/verlet_integration.md
Labels: Implementation Edit

#372 Updating Error Calculation for Monte Carlo in Javascript
  contents/monte_carlo_integration/code/javascript/monte_carlo.js
Labels: Implementation Edit

#322 Added Thomas Algorithm in Scratch
  contents/thomas_algorithm/code/scratch/thomas.svg
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation

#374 Fixing percentage error in monte_carlo.c
  contents/monte_carlo_integration/code/c/monte_carlo.c
Labels: Implementation Edit

#299 Update C++ implementations for Verlet algorithms
  contents/verlet_integration/code/c++/verlet.cpp
  contents/verlet_integration/verlet_integration.md
Labels: Implementation Edit

#378 Fix compilation error in bogosort C++
  contents/bogo_sort/code/c++/bogosort.cpp
Labels: Implementation Edit

#381 Fixing percent error in monte_carlo.rs
  contents/monte_carlo_integration/code/rust/monte_carlo.rs
Labels: Implementation Edit

#302 fix grammar
  CONTRIBUTORS.md
  README.md
  contents/gaussian_elimination/gaussian_elimination.md
  contents/git_and_version_control/git_and_version_control.md
  contents/my_introduction_to_hobby_programming/my_introduction_to_hobby_programming.md
Labels: Small Changes

#386 Updating Monte Carlo in Swift 4.1 to Swift 4.2
  contents/monte_carlo_integration/code/swift/monte_carlo.swift
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation Edit

#385 Updating Bogo Sort in Swift 4.1 to Swift 4.2
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/swift/bogosort.swift
Labels: Implementation Edit

#382 Adding DFT to python and fixing code examples for FFT.
  contents/cooley_tukey/code/python/fft.py
  contents/cooley_tukey/cooley_tukey.md
Labels: Implementation Edit, Small Changes

#380 Update forward Euler method in Julia for v1
  contents/forward_euler_method/code/julia/euler.jl
Labels: Implementation Edit

#370 Implement gaussian elimination in python
  contents/gaussian_elimination/code/python/gaussian_elimination.py
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Implementation

#363 Monte Carlo integration Fortran 90
  CONTRIBUTORS.md
  book.json
  contents/monte_carlo_integration/code/fortran/monte_carlo.f90
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation

#316 Use Travis CI to test the book build and then deploy it to the site, take 2
  .travis.yml
  tools/deploy/update_site_travis.bash
Labels: General

#389 Update all julia code to V1.0
  contents/cooley_tukey/code/julia/fft.jl
  contents/cooley_tukey/cooley_tukey.md
  contents/gaussian_elimination/code/julia/gaussian_elimination.jl
  contents/gaussian_elimination/gaussian_elimination.md
  contents/graham_scan/code/julia/graham.jl
  contents/split-operator_method/code/julia/split_op.jl
  contents/split-operator_method/split-operator_method.md
  contents/stable_marriage_problem/code/julia/stable_marriage.jl
  contents/tree_traversal/code/julia/Tree.jl
Labels: Implementation Edit

#369 Euclidean's algorithm in Fortran90
  CONTRIBUTORS.md
  contents/euclidean_algorithm/code/fortran/euclidean.f90
  contents/euclidean_algorithm/code/fortran/interactive_euclidean.f90
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation

#377 Tiny Tiny Edit to Thomas Algorithm in Python
  contents/thomas_algorithm/code/python/thomas.py
Labels: Implementation Edit

#390 Bubblesort Fortran 90
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/fortran/bubble.f90
Labels: Implementation

#362 implement fft in clojure
  contents/cooley_tukey/code/clojure/fft.clj
  contents/cooley_tukey/cooley_tukey.md
Labels: Implementation

#383 Adding Thomas Algorithm in Swift
  contents/thomas_algorithm/code/swift/thomas.swift
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation
