Repository algorithm-archivists/algorithm-archive, pull requests merged in 2018-07, with the labels that each got.

#192 add monte carlo in clojure
  chapters/monte_carlo/code/clojure/monte_carlo.clj
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#158 euler.m
  chapters/differential_equations/euler/code/euler.m
Labels: Implementation

#188 Added MonteCarlo in Java
  CONTRIBUTORS.md
  chapters/monte_carlo/code/java/MonteCarlo.java
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#194 Tidy up code imports
  chapters/FFT/cooley_tukey.md
  chapters/sorting_searching/bogo/bogo_sort.md
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/tree_traversal/code/python/Tree_example.py
  chapters/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#186 Correct bogosort's best case runtime
  chapters/sorting_searching/bogo/bogo_sort.md
Labels: Chapter Edit

#177 Added EditorConfig rule for Matlab and Racket source files
  .editorconfig
Labels: General

#198 Remove unused "differential_equations.md" and "math.md".
  chapters/differential_equations.md
Labels: Chapter Edit, General

#183 Added rust implementation of gaussian elimination
  chapters/matrix_methods/gaussian_elimination/code/rust/gaussian_elimination.rs
  chapters/matrix_methods/gaussian_elimination/gaussian_elimination.md
Labels: Implementation

#197 Added Monte Carlo in Swift 4.1
  chapters/monte_carlo/code/swift/monte_carlo.swift
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#203 Added forward euler in python3
  chapters/differential_equations/euler/code/python/euler.py
  chapters/differential_equations/euler/euler.md
Labels: Implementation

#204 Modified euclidian algorithm haskell code to be more clear and readable
  CONTRIBUTORS.md
  chapters/euclidean_algorithm/code/haskell/euclidean_example.hs
  chapters/euclidean_algorithm/euclidean.md
Labels: Implementation Edit

#170 Fix the size of the diagrams. Add res folders.
  chapters/FFT/cooley_tukey.md
  chapters/data_compression/huffman/huffman.md
  chapters/differential_equations/euler/euler.md
  chapters/euclidean_algorithm/euclidean.md
  chapters/monte_carlo/monte_carlo.md
  chapters/physics_solvers/verlet/verlet.md
  chapters/principles_of_code/building_blocks/bitlogic.md
  chapters/principles_of_code/building_blocks/res/and.jpg
  chapters/principles_of_code/building_blocks/res/nand.jpg
  chapters/principles_of_code/building_blocks/res/nor.jpg
  chapters/principles_of_code/building_blocks/res/not.jpg
  chapters/principles_of_code/building_blocks/res/or.jpg
  chapters/principles_of_code/building_blocks/res/xor.jpg
  chapters/principles_of_code/notation/notation.md
  chapters/principles_of_code/notation/res/cplot.png
  chapters/principles_of_code/res/clone.png
  chapters/principles_of_code/res/fork.png
  chapters/principles_of_code/version_control.md
  chapters/taylor/res/function_sum.png
  chapters/taylor/taylor_series.md
  chapters/tree_traversal/tree_traversal.md
  styles/website.css
Labels: Chapter Edit

#182 Add rust implementation of forward euler
  CONTRIBUTORS.md
  chapters/differential_equations/euler/code/rust/euler.rs
  chapters/differential_equations/euler/euler.md
Labels: Implementation

#191 thomas python example
  CONTRIBUTORS.md
  chapters/matrix_methods/thomas/code/python/thomas.py
  chapters/matrix_methods/thomas/thomas.md
Labels: Implementation

#210 Small Change to Java implementation of Monte Carlo
  chapters/monte_carlo/code/java/MonteCarlo.java
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation Edit

#208 Fix Swift and JavaScript code imports.
  chapters/monte_carlo/monte_carlo.md
Labels: Small Changes

#209 Update Tree Traversal C#.
  chapters/tree_traversal/code/cs/Program.cs
  chapters/tree_traversal/code/cs/Tree.cs
  chapters/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#195 Adding Gaussian Elimination and Thomas Algorithm in C.
  chapters/matrix_methods/gaussian_elimination/code/c/gaussian_elimination.c
  chapters/matrix_methods/gaussian_elimination/gaussian_elimination.md
  chapters/matrix_methods/thomas/code/c/thomas.c
  chapters/matrix_methods/thomas/thomas.md
Labels: Implementation

#206 R monte carlo
  CONTRIBUTORS.md
  chapters/monte_carlo/code/R/monte_carlo.R
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#220 Use our version of the theme-api plugin to get automatically ordered languages
  book.json
  book_ace.json
Labels: General

#221 Added JSON to .editorconfig and converted all JSON files
  .editorconfig
  chapters/differential_equations/euler/code/elm/elm-package.json
Labels: General

#225 make every contributor's name apear on a new line
  CONTRIBUTORS.md
Labels: General

#224 Renamed some language code dirs for consistency
  chapters/FFT/code/haskell/fft.hs
  chapters/FFT/cooley_tukey.md
  chapters/computational_geometry/gift_wrapping/jarvis_march/code/csharp/JarvisMarch.cs
  chapters/computational_geometry/gift_wrapping/jarvis_march/code/csharp/Program.cs
  chapters/computational_geometry/gift_wrapping/jarvis_march/jarvis_march.md
  chapters/data_compression/huffman/code/csharp/HuffmanCoding.cs
  chapters/data_compression/huffman/code/csharp/Program.cs
  chapters/data_compression/huffman/huffman.md
  chapters/decision_problems/stable_marriage/code/csharp/GaleShapleyAlgorithm.cs
  chapters/decision_problems/stable_marriage/code/csharp/ListExtensions.cs
  chapters/decision_problems/stable_marriage/code/csharp/Person.cs
  chapters/decision_problems/stable_marriage/code/csharp/Program.cs
  chapters/decision_problems/stable_marriage/stable_marriage.md
  chapters/euclidean_algorithm/code/csharp/EuclideanAlgorithm.cs
  chapters/euclidean_algorithm/code/csharp/Program.cs
  chapters/euclidean_algorithm/euclidean.md
  chapters/monte_carlo/code/javascript/monte_carlo.js
  chapters/monte_carlo/code/r/monte_carlo.R
  chapters/monte_carlo/monte_carlo.md
  chapters/sorting_searching/bogo/bogo_sort.md
  chapters/sorting_searching/bogo/code/csharp/BogoSort.cs
  chapters/sorting_searching/bogo/code/csharp/Program.cs
  chapters/sorting_searching/bogo/code/javascript/bogo.js
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/csharp/BubbleSort.cs
  chapters/sorting_searching/bubble/code/csharp/Program.cs
  chapters/sorting_searching/bubble/code/javascript/bubble.js
  chapters/tree_traversal/code/csharp/Program.cs
  chapters/tree_traversal/code/csharp/Tree.cs
  chapters/tree_traversal/tree_traversal.md
Labels: General

#227 Cleaned up the code a bit
  chapters/euclidean_algorithm/code/python/euclidean_example.py
Labels: Implementation Edit

#223 Python implementation for Jarvis March
  CONTRIBUTORS.md
  chapters/computational_geometry/gift_wrapping/jarvis_march/code/py/jarvisMarch.py
  chapters/computational_geometry/gift_wrapping/jarvis_march/jarvis_march.md
Labels: Implementation

#215 Added Forward Euler to Haskell
  chapters/differential_equations/euler/code/haskell/euler.hs
  chapters/differential_equations/euler/euler.md
Labels: Implementation

#232 Adding a missing line of code in euclidean.md
  chapters/euclidean_algorithm/euclidean.md
Labels: Small Changes

#237 Replaced duplicate point from test example
  chapters/computational_geometry/gift_wrapping/jarvis_march/code/py/jarvisMarch.py
Labels: Implementation Edit

#233 Adding main() to Swift sorting algorithms
  chapters/sorting_searching/bogo/code/swift/bogosort.swift
  chapters/sorting_searching/bubble/bubble_sort.md
Labels: Implementation Edit

#231 Adding Euclidean Algorithm in Swift
  chapters/euclidean_algorithm/code/swift/euclidean_algorithm.swift
  chapters/euclidean_algorithm/euclidean.md
Labels: Implementation

#247 Fix "cooley_turkey" to "cooley_tukey".
  SUMMARY.md
  chapters/algorithms/convolutions/convolutions.md
  chapters/algorithms/cooley_tukey/code/c++/fft.cpp
  chapters/algorithms/cooley_tukey/code/c/fft.c
  chapters/algorithms/cooley_tukey/code/haskell/fft.hs
  chapters/algorithms/cooley_tukey/code/julia/fft.jl
  chapters/algorithms/cooley_tukey/code/python/fft.py
  chapters/algorithms/cooley_tukey/cooley_tukey.md
  chapters/algorithms/cooley_tukey/res/FT_example.png
  chapters/algorithms/cooley_tukey/res/butterfly_diagram.png
  chapters/algorithms/cooley_tukey/res/fft.png
  chapters/algorithms/cooley_tukey/res/out.dat
  chapters/algorithms/cooley_tukey/res/radix-2screen.jpg
  chapters/algorithms/cooley_tukey/res/radix-2screen_positive.jpg
  chapters/algorithms/cooley_tukey/res/radix-8screen.jpg
  chapters/algorithms/cooley_tukey/res/sinusoid.png
  chapters/algorithms/split-operator_method/split-operator_method.md
  chapters/general/quantum_systems/quantum_systems.md
  redirects.json
Labels: Small Changes

#246 Removing All Language Headlines
  chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md
  chapters/algorithms/forward_euler_method/forward_euler_method.md
  chapters/algorithms/gaussian_elimination/gaussian_elimination.md
  chapters/algorithms/graham_scan/graham_scan.md
  chapters/algorithms/huffman_encoding/huffman_encoding.md
  chapters/algorithms/jarvis_march/jarvis_march.md
  chapters/algorithms/monte_carlo_integration/monte_carlo_integration.md
  chapters/algorithms/split-operator_method/split-operator_method.md
  chapters/algorithms/stable_marriage_problem/stable_marriage_problem.md
  chapters/algorithms/thomas_algorithm/thomas_algorithm.md
  chapters/algorithms/tree_traversal/tree_traversal.md
  chapters/algorithms/verlet_integration/verlet_integration.md
Labels: Chapter Edit, General

#243 Improve readability of examples in verlet.cpp
  chapters/algorithms/verlet_integration/code/c++/verlet.cpp
  chapters/algorithms/verlet_integration/verlet_integration.md
Labels: Implementation Edit

#234 Changes to Euclidean Algorithm in Java
  chapters/algorithms/euclidean_algorithm/code/java/EuclideanAlgo.java
  chapters/algorithms/euclidean_algorithm/code/java/MainClass.java
  chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation Edit

#252 Move "euler.m" to a new matlab code directory and import the matlab euler code into the euler markdown.
  chapters/algorithms/forward_euler_method/code/matlab/euler.m
  chapters/algorithms/forward_euler_method/forward_euler_method.md
Labels: Small Changes

#219 updating gaussian elimination to be more general
  chapters/algorithms/gaussian_elimination/code/julia/gaussian_elimination.jl
  chapters/algorithms/gaussian_elimination/gaussian_elimination.md
Labels: Chapter Edit, Implementation Edit

#262 Extraneous assignment in Julia implementation of Graham Scan
  chapters/algorithms/graham_scan/code/julia/graham.jl
  chapters/algorithms/graham_scan/graham_scan.md
Labels: Implementation Edit

#266 Julia verlet update
  chapters/algorithms/verlet_integration/code/julia/verlet.jl
Labels: Implementation Edit

#254 Match bubble sort C implementation with Julia
  chapters/algorithms/bubble_sort/bubble_sort.md
  chapters/algorithms/bubble_sort/code/c/bubble_sort.c
Labels: Implementation Edit

#250 removing principles of code chapter, updating book
  SUMMARY.md
  TODO.md
  chapters/algorithms/backward_euler_method/backward_euler_method.md
  chapters/algorithms/forward_euler_method/forward_euler_method.md
  chapters/algorithms/verlet_integration/verlet_integration.md
  chapters/data_structures/data_structures.md
  chapters/data_structures/stacks_and_queues/stacks_and_queues.md
  chapters/general/bitlogic/bitlogic.md
  chapters/general/bitlogic/res/and.jpg
  chapters/general/bitlogic/res/nand.jpg
  chapters/general/bitlogic/res/nor.jpg
  chapters/general/bitlogic/res/not.jpg
  chapters/general/bitlogic/res/or.jpg
  chapters/general/bitlogic/res/xor.jpg
  chapters/general/differential_equations/differential_equations.md
  chapters/general/mathematical_background/mathematical_background.md
  chapters/general/notation/notation.md
  chapters/general/notation/out.dat
  chapters/general/notation/res/cplot.png
  chapters/general/physics_solvers/physics_solvers.md
  chapters/introduction/how_to_contribute.md
  chapters/introduction/res/clone.png
  chapters/introduction/res/fork.png
  chapters/introduction/version_control.md
  chapters/languages/choosing_a_language.md
  chapters/languages/compiled/FORTRAN.md
  chapters/languages/compiled/compiled.md
  chapters/languages/compiled/makefiles.md
  chapters/principles_of_code/building_blocks/building_blocks.md
  chapters/principles_of_code/building_blocks/classes.md
  chapters/principles_of_code/building_blocks/conditions.md
  chapters/principles_of_code/building_blocks/functions.md
  chapters/principles_of_code/building_blocks/loops.md
  chapters/principles_of_code/building_blocks/variables.md
  chapters/principles_of_code/code_quality.md
  chapters/principles_of_code/principles_of_code.md
  redirects.json
Labels: Chapter, General

#272 Bubble Sort in TI-83 Basic
  CONTRIBUTORS.md
  book.json
  chapters/algorithms/bubble_sort/bubble_sort.md
  chapters/algorithms/bubble_sort/code/ti83basic/BUBLSORT.txt
Labels: Implementation

#270 Optional hooks to prevent committing/pushing to master
  tools/hooks/README.md
  tools/hooks/install_hooks.bash
  tools/hooks/pre-commit.hook
Labels: General

#281 Fixed the broken build
  chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md
Labels: General

#280 Added a note in README.md for new contributors
  README.md
Labels: General

#282 Small .md Fixes for 'Example Code'
  contents/euclidean_algorithm/euclidean_algorithm.md
  contents/huffman_encoding/huffman_encoding.md
Labels: Small Changes

#238 Python implementation for Graham Scan
  contents/graham_scan/code/python/grahamScan.py
  contents/graham_scan/graham_scan.md
Labels: Implementation

#255 Adding Forward Euler in Swift
  contents/forward_euler_method/code/swift/euler.swift
  contents/forward_euler_method/forward_euler_method.md
Labels: Implementation

#240 Adding Example Code to Sorting Algorithms
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/java/bogo.java
  contents/bogo_sort/code/javascript/bogo.js
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/java/bubble.java
Labels: Implementation Edit

#256 Reimplemented Verlet Integration in Python
  contents/verlet_integration/code/python/verlet.py
  contents/verlet_integration/verlet_integration.md
Labels: Implementation Edit

#286 Create CONTRIBUTING.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: General

#288 Adjusting Whitespace in Swift Code
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/swift/bogosort.swift
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/swift/bubblesort.swift
  contents/forward_euler_method/code/swift/euler.swift
  contents/monte_carlo_integration/code/swift/monte_carlo.swift
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation Edit, Small Changes

#244 Cleanup bubble sort code for C++
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/c++/bubblesort.cpp
Labels: Implementation Edit

#298 Update C implementations for Verlet algorithms
  contents/verlet_integration/code/c/verlet.c
  contents/verlet_integration/verlet_integration.md
Labels: Implementation Edit

#296 Update for Tree Traversal with Scratch
  contents/tree_traversal/code/scratch/bfs.svg
  contents/tree_traversal/code/scratch/dfs-from.svg
  contents/tree_traversal/code/scratch/dfs-in.svg
  contents/tree_traversal/code/scratch/dfs-post.svg
  contents/tree_traversal/code/scratch/dfs-stack.svg
  contents/tree_traversal/code/scratch/dfs.svg
  contents/tree_traversal/code/scratch/scratch_tree.png
  contents/tree_traversal/code/scratch/struct.svg
  contents/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#130 Implement bubble sort in Ruby
  CONTRIBUTORS.md
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/ruby/bubble.rb
Labels: Implementation

#293 Adding Euclidean Algorithm in Lua
  book.json
  contents/euclidean_algorithm/code/lua/euclidean.lua
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation

#249 Split op updates
  contents/quantum_systems/code/julia/energy.jl
  contents/quantum_systems/quantum_systems.md
  contents/quantum_systems/res/gaussian.gif
  contents/split-operator_method/code/julia/split_op.jl
  contents/split-operator_method/res/Psi_t.png
  contents/split-operator_method/res/Psi_tdt.png
  contents/split-operator_method/res/imaginary_time.gif
  contents/split-operator_method/res/imaginary_time.png
  contents/split-operator_method/res/imaginary_time_0.png
  contents/split-operator_method/res/imaginary_time_75.png
  contents/split-operator_method/res/real_time.gif
  contents/split-operator_method/res/real_time.png
  contents/split-operator_method/res/real_time_0.png
  contents/split-operator_method/res/real_time_75.png
  contents/split-operator_method/res/split_op_method.svg
  contents/split-operator_method/res/times_Uk.png
  contents/split-operator_method/res/times_Ur.png
  contents/split-operator_method/split-operator_method.md
Labels: Chapter Edit, Discussion, Implementation Edit

#284 Automatically build book and deploy to a repo
  .travis.yml
  tools/deploy/update_site_travis.bash
Labels: General

#193 Added Gaussian Elimination in Haskell
  contents/gaussian_elimination/code/haskell/gaussianElimination.hs
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Implementation
