Repository algorithm-archivists/algorithm-archive, pull requests merged in 2018-08, with the labels that each got.

#319 Added Bubble Sort in Crystal
  CONTRIBUTORS.md
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/crystal/bubble.cr
Labels: Implementation

#323 Rename directory from "py" to "python" for the sake of consistency and complying to the guidelines.
  contents/jarvis_march/code/python/jarvisMarch.py
  contents/jarvis_march/jarvis_march.md
Labels: Small Changes

#309 Add Monte Carlo Integration in C#
  contents/monte_carlo_integration/code/csharp/Circle.cs
  contents/monte_carlo_integration/code/csharp/MonteCarlo.cs
  contents/monte_carlo_integration/code/csharp/Program.cs
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation

#321 Added Thomas Algorithm in Haskell
  contents/thomas_algorithm/code/haskell/thomas.hs
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation

#283 Added Jarvis March for C++
  CONTRIBUTORS.md
  contents/jarvis_march/code/c++/jarvis_march.cpp
  contents/jarvis_march/jarvis_march.md
Labels: Implementation

#287 Minor improvement in Gaussian Elimination in Julia
  contents/gaussian_elimination/code/julia/gaussian_elimination.jl
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Implementation Edit

#275 Minor clean up for Forward Euler Method in C++
  contents/forward_euler_method/code/c++/euler.cpp
Labels: Implementation Edit

#312 Added mathjax reference on algorithm-archivists/plugin-mathjax
  book.json
Labels: General

#326 Adding the Missing Rust Tree Traversal Functions
  contents/tree_traversal/code/rust/tree.rs
  contents/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#327 Fix typo.
  README.md
  contents/bitlogic/bitlogic.md
  contents/cooley_tukey/cooley_tukey.md
  contents/euclidean_algorithm/euclidean_algorithm.md
  contents/forward_euler_method/forward_euler_method.md
  contents/git_and_version_control/git_and_version_control.md
  contents/graham_scan/graham_scan.md
  contents/how_to_contribute/how_to_contribute.md
  contents/introduction/introduction.md
  contents/mathematical_background/mathematical_background.md
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/multiplication/multiplication.md
  contents/physics_solvers/physics_solvers.md
  contents/quantum_systems/quantum_systems.md
  contents/verlet_integration/verlet_integration.md
Labels: Small Changes

#333 Add QM energy in Python
  contents/quantum_systems/code/python/energy.py
  contents/quantum_systems/quantum_systems.md
Labels: Implementation

#332 Add split-operator method in Python
  contents/split-operator_method/code/python/split_op.py
  contents/split-operator_method/split-operator_method.md
Labels: Implementation

#308 Adding split_op.c and energy.c
  contents/quantum_systems/code/c/energy.c
  contents/quantum_systems/quantum_systems.md
  contents/split-operator_method/code/c/split_op.c
  contents/split-operator_method/split-operator_method.md
Labels: Implementation

#336 Fix typo in Rust tree traversal
  contents/tree_traversal/code/rust/tree.rs
Labels: Implementation Edit

#329 Re-wrote Thomas Algorithm chapter to include more details
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Chapter Edit

#317 Adding Tree Traversal in Swift
  contents/tree_traversal/code/swift/tree.swift
  contents/tree_traversal/tree_traversal.md
Labels: Implementation

#285 Thomas algorithm in java
  contents/thomas_algorithm/code/java/thomas.java
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation

#315 Changed referecne of api-language-plugin to archive-archivist version
  book.json
Labels: General

#342 Implement C++ version of Monte Carlo integration
  CONTRIBUTORS.md
  contents/monte_carlo_integration/code/c++/monte_carlo.cpp
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation

#343 Bogo sort in PHP
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/php/bogo_sort.php
Labels: Implementation

#351 Fix website.css
  styles/website.css
Labels: Small Changes

#338 Adding Formatting to File Names
  contents/bogo_sort/bogo_sort.md
  contents/bubble_sort/bubble_sort.md
  contents/euclidean_algorithm/euclidean_algorithm.md
  contents/huffman_encoding/huffman_encoding.md
  contents/jarvis_march/jarvis_march.md
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/stable_marriage_problem/stable_marriage_problem.md
  contents/tree_traversal/tree_traversal.md
Labels: Small Changes

#353 implemented euclid algorithm in nim
  CONTRIBUTORS.md
  book.json
  contents/euclidean_algorithm/code/nim/euclid_algorithm.nim
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation

#349 Added Euclidean Algorithm for lisp
  contents/euclidean_algorithm/code/lisp/euclidean_algorithm.lisp
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation

#348 Added Lisp implementation for bubble sort
  .editorconfig
  CONTRIBUTORS.md
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/lisp/bubble_sort.lisp
Labels: Implementation

#350 Bubble sort: run MATLAB implementation and Markdown fixes
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/matlab/bubblesort.m
  contents/bubble_sort/code/racket/bubbleSort.rkt
Labels: Implementation Edit

#355 implemented bogo sort in nim
  book.json
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/nim/bogo_sort.nim
Labels: Implementation

#356 implemented monte carlo integration in nim
  contents/monte_carlo_integration/code/nim/monte_carlo.nim
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation

#341 Adding the missing examples of Tree Traversal to C++
  contents/tree_traversal/code/c++/tree_example.cpp
  contents/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#344 PHP Tree Traversal
  contents/tree_traversal/code/php/tree_traversal.php
  contents/tree_traversal/tree_traversal.md
Labels: Implementation

#359 implemented bubble sort in nim
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/nim/bubble_sort.nim
Labels: Implementation

#291 Implementation Edit to Bogo Sort in Javascript
  contents/bogo_sort/code/javascript/bogo.js
Labels: Implementation Edit

#292 Implementation Edit to Bubble Sort in Javascript
  contents/bubble_sort/code/javascript/bubble.js
Labels: Implementation Edit

#276 Minor clean up for cooley tukey in C++
  contents/cooley_tukey/code/c++/fft.cpp
  contents/cooley_tukey/cooley_tukey.md
Labels: Implementation Edit

#263 Adding Verlet Integration in Swift
  contents/verlet_integration/code/swift/verlet.swift
  contents/verlet_integration/verlet_integration.md
Labels: Implementation

#297 Update Rust implementations for Verlet algorithms
  contents/verlet_integration/code/julia/verlet.jl
  contents/verlet_integration/code/rust/verlet.rs
  contents/verlet_integration/verlet_integration.md
Labels: Chapter Edit, Implementation Edit
