Repository algorithm-archivists/algorithm-archive, pull requests merged in 2018-06, with the labels that each got.

#112 Added Graham Scan in Haskell
  chapters/computational_geometry/gift_wrapping/graham_scan/code/haskell/grahamScan.hs
  chapters/computational_geometry/gift_wrapping/graham_scan/graham_scan.md
Labels: Algorithm, Chapter Edit

#124 Fixing stable_marriage.c and convolutions.c
  chapters/convolutions/code/c/convolutions.c
  chapters/convolutions/code/c/fft.h
  chapters/convolutions/convolutions.md
  chapters/decision_problems/stable_marriage/code/c/stable_marriage.c
Labels: Implementation Edit

#132 Fixed a typo
  chapters/data_compression/data_compression.md
Labels: Chapter Edit

#135 Added .java files to .editorconfig
  .editorconfig
Labels: General

#147 Added a rust version of the monte carlo example
  chapters/monte_carlo/code/rust/monte_carlo.rs
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#150 Spelling correction
  TODO.md
Labels: Chapter Edit

#151 Spelling correction
  chapters/principles_of_code/building_blocks/bitlogic.md
Labels: Chapter Edit

#139 Add d language example to bubble sort
  book.json
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/d/bubble_sort.d
Labels: Implementation

#155 Added EditorConfig rules for .d files
  .editorconfig
Labels: General

#136 Added Rust implementation of bubble sort.
  CONTRIBUTORS.md
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/rust/bubble_sort.rs
Labels: Implementation

#121 Adding a C Monte Carlo implementation.
  chapters/monte_carlo/code/c/monte_carlo.c
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#120 Enhance the code of TreeTraversal and EuclideanAlgorithm for C#
  chapters/euclidean_algorithm/code/cs/EuclideanAlgorithm.cs
  chapters/euclidean_algorithm/code/cs/EuclideanAlgorithmMdAdditional/EuclideanAlgorithmMdAdditional.cs
  chapters/euclidean_algorithm/code/cs/EuclideanAlgorithmMdAdditional/Program.cs
  chapters/euclidean_algorithm/code/cs/Program.cs
  chapters/euclidean_algorithm/euclidean.md
  chapters/tree_traversal/code/cs/Program.cs
  chapters/tree_traversal/code/cs/Tree.cs
  chapters/tree_traversal/code/cs/Tree/Program.cs
  chapters/tree_traversal/code/cs/TreeMdAdditional/Program.cs
  chapters/tree_traversal/code/cs/TreeMdAdditional/TreeMdAdditional.cs
  chapters/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#131 Added the java version of the bubble algorithm
  CONTRIBUTORS.md
  chapters/sorting_searching/bogo/bogo_sort.md
  chapters/sorting_searching/bogo/code/java/bogo.java
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/java/bubble.java
Labels: Implementation

#157 Add Go language to bubble sort
  book.json
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/go/bubbleSort.go
Labels: Implementation

#162 Add D implementation of monte carlo
  chapters/monte_carlo/code/d/monte_carlo.d
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation

#145 General python support
  book.json
  chapters/FFT/code/python/fft.py
  chapters/FFT/cooley_tukey.md
  chapters/euclidean_algorithm/code/python/euclidean_example.py
  chapters/euclidean_algorithm/euclidean.md
  chapters/physics_solvers/verlet/code/python/verlet.py
  chapters/physics_solvers/verlet/verlet.md
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/python/bubblesort.py
  chapters/tree_traversal/code/python/Tree_example.py
  chapters/tree_traversal/code/python3/Tree_example.py
  chapters/tree_traversal/tree_traversal.md
Labels: Implementation, Implementation Edit

#166 Added Matlab bubblesort
  book.json
  chapters/sorting_searching/bogo/bogo_sort.md
  chapters/sorting_searching/bogo/code/matlab/bogosort.m
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/matlab/bubblesort.m
Labels: Implementation

#164 Racket implementation for Bubble Sort
  CONTRIBUTORS.md
  book.json
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/racket/bubbleSort.rkt
Labels: Implementation

#169 Add missing comma.
  book.json
Labels: Some other Fix

#168 Removed unnessesary temp variable
  chapters/euclidean_algorithm/code/python/euclidean_example.py
  chapters/euclidean_algorithm/euclidean.md
Labels: Implementation Edit

#149 Implementation of Tree Traversal in java
  chapters/tree_traversal/code/java/MainClass.java
  chapters/tree_traversal/code/java/Tree.java
  chapters/tree_traversal/tree_traversal.md
Labels: Implementation

#142 Added python Bogo Sort
  CONTRIBUTORS.md
  chapters/sorting_searching/bogo/bogo_sort.md
  chapters/sorting_searching/bogo/code/python/bogo.py
Labels: Implementation

#161 Added BogoSort in Swift 4.1
  CONTRIBUTORS.md
  book.json
  chapters/sorting_searching/bogo/bogo_sort.md
  chapters/sorting_searching/bogo/code/swift/bogosort.swift
Labels: Implementation

#172 DFS_inorder julia update for tree traversal
  chapters/tree_traversal/code/julia/Tree.jl
Labels: Implementation Edit

#178 simplifying Julia code for Monte Carlo
  chapters/monte_carlo/code/julia/monte_carlo.jl
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation Edit

#180 Adding Bubble Sort in Swift
  chapters/sorting_searching/bubble/bubble_sort.md
  chapters/sorting_searching/bubble/code/swift/bubblesort.swift
Labels: Implementation

#181 Added java implementation of Huffman compression
  CONTRIBUTORS.md
  chapters/data_compression/huffman/code/java/huffman.java
  chapters/data_compression/huffman/huffman.md
Labels: Implementation

#175 Added monte carlo javascript example
  chapters/monte_carlo/code/js/monte_carlo.js
  chapters/monte_carlo/monte_carlo.md
Labels: Implementation
