Repository algorithm-archivists/algorithm-archive, pull requests merged in 2018-10, with the labels that each got.

#401 Fix NOT-gate image to include inverter bubble
  contents/bitlogic/res/not.jpg
Labels: Chapter Edit, Hacktoberfest

#416 Fix typo in fortran syntax highlighting declaration
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Small Changes

#419 Fixed line numbers for C lang for the split operator markdown
  contents/split-operator_method/split-operator_method.md
Labels: Hacktoberfest, Small Changes

#422 adding smallscale fix to .travis.yml file.
  .travis.yml
Labels: Problem

#395 Haskell: added DFS Stack to Tree Traversal
  contents/tree_traversal/code/haskell/TreeTraversal.hs
  contents/tree_traversal/tree_traversal.md
Labels: Hacktoberfest, Implementation Edit

#398 Haskell: added Stormer Verlet and Velocity Verlet
  contents/verlet_integration/code/haskell/verlet.hs
  contents/verlet_integration/verlet_integration.md
Labels: Hacktoberfest, Implementation Edit

#396 Haskell: added FFT method for convolution
  contents/convolutions/code/haskell/convolution.hs
  contents/convolutions/convolutions.md
Labels: Hacktoberfest, Implementation Edit

#423 Emojicode bubble sort implementation.
  .editorconfig
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/emojicode/bubble_sort.emojic
Labels: Hacktoberfest, Implementation

#437 Making the Ruby bogosort more idiomatic
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/ruby/bogo.rb
Labels: Hacktoberfest, Implementation Edit

#417 Bubble sort in scala implementation
  CONTRIBUTORS.md
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/scala/bubble_sort.scala
Labels: Hacktoberfest, Implementation

#433 Euclidean algorithm racket
  CONTRIBUTORS.md
  contents/euclidean_algorithm/code/racket/euclidean_algorithm.rkt
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#442 Added EditorConfig for PHP from Symfony coding standard
  .editorconfig
Labels: General

#421 Bogosort fortran
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/fortran/bogo.f90
Labels: Hacktoberfest, Implementation

#439 add thomas alg in C++
  contents/thomas_algorithm/code/c++/thomas.cpp
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Hacktoberfest, Implementation

#455 Small change to assembly code formating
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/asm-x64/bubble_sort.s
Labels: Small Changes

#406 add tree traversal in golang
  contents/tree_traversal/code/golang/treetraversal.go
  contents/tree_traversal/tree_traversal.md
Labels: Hacktoberfest, Implementation

#399 added thomas alg in nim
  contents/thomas_algorithm/code/nim/thomas_algorithm.nim
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Hacktoberfest, Implementation

#454 Euclidean algorithm for Smalltalk.
  contents/euclidean_algorithm/code/smalltalk/euclid.st
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#447 Add Euclidean algorithm in Ruby
  contents/euclidean_algorithm/code/ruby/euclidean.rb
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#451 Added bubble sort for smalltalk
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/smalltalk/bubble.st
Labels: Hacktoberfest, Implementation

#452 Added bogo sort for smalltalk
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/smalltalk/bogosort.st
Labels: Hacktoberfest, Implementation

#462 fixed formatting in nim bubblesort
  contents/bubble_sort/code/nim/bubble_sort.nim
Labels: Hacktoberfest, Implementation Edit

#466 change formatting in euclid alg in nim
  contents/euclidean_algorithm/code/nim/euclid_algorithm.nim
Labels: Hacktoberfest, Implementation

#449 Add Huffman encoding example in x86-64 assembly
  book.json
  contents/huffman_encoding/code/asm-x64/huffman.s
  contents/huffman_encoding/huffman_encoding.md
Labels: Hacktoberfest, Implementation

#470 Add some texteditors to the gitignore
  .gitignore
Labels: General

#465 Add Bubble Sort implementation in Kotlin
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/kotlin/BubbleSort.kt
Labels: Hacktoberfest, Implementation

#458 Monte carlo implementation in scala
  contents/monte_carlo_integration/code/monte_carlo.scala
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#444 Add Monte Carlo integration in Racket
  contents/monte_carlo_integration/code/racket/monte_carlo.rkt
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#457 Monte Carlo in Lua
  .editorconfig
  contents/bogo_sort/code/lua/bogosort.lua
  contents/bubble_sort/code/lua/bubble_sort.lua
  contents/monte_carlo_integration/code/lua/monte_carlo.lua
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#414 Brainfuck Bubble sort
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/brainfuck/bubblesort.bf
Labels: Hacktoberfest, Implementation

#473 renaming scala file so book builds correctly.
  contents/monte_carlo_integration/code/scala/monte_carlo.scala
Labels: General, Hacktoberfest

#475 C quantum system fixes
  contents/quantum_systems/code/c/energy.c
  contents/quantum_systems/quantum_systems.md
Labels: Hacktoberfest, Implementation Edit

#429 Implementation Thomas algorithm in PHP
  contents/thomas_algorithm/code/php/thomas.php
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Hacktoberfest, Implementation

#415 Whitespace: added Euclidian algorithm
  .editorconfig
  book.json
  contents/euclidean_algorithm/code/whitespace/euclidian_mod.ws
  contents/euclidean_algorithm/code/whitespace/euclidian_mod_comments.ws
  contents/euclidean_algorithm/code/whitespace/euclidian_sub.ws
  contents/euclidean_algorithm/code/whitespace/euclidian_sub_comments.ws
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#431 Added intergration of Monte Carlo for PHP
  contents/monte_carlo_integration/code/php/monte_carlo.php
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#469 Euclid algorithm in lolcode
  .editorconfig
  book.json
  contents/euclidean_algorithm/code/lolcode/euclid.lol
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#426 Add Bogosort in Factor
  CONTRIBUTORS.md
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/factor/bogo_sort.factor
Labels: Hacktoberfest, Implementation

#425 Add Euclidean GCD in Factor
  .editorconfig
  book.json
  contents/euclidean_algorithm/code/factor/euclid.factor
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#483 Add Monte Carlo Integration in Emojicode.
  contents/monte_carlo_integration/code/emojicode/monte_carlo.emojic
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#430 Added implementation for euclidean algorithm in PHP
  contents/euclidean_algorithm/code/php/euclidean.php
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#480 Improved some JavaScript examples
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/javascript/bubble.js
  contents/euclidean_algorithm/code/javascript/euclidean_example.js
  contents/verlet_integration/code/javascript/verlet.js
  contents/verlet_integration/verlet_integration.md
Labels: Hacktoberfest, Implementation

#428 Implementation Stable marriage problem in PHP
  contents/stable_marriage_problem/code/php/stable_marriage.php
  contents/stable_marriage_problem/stable_marriage_problem.md
Labels: Hacktoberfest, Implementation

#424 Add Emojicode Bogo Sort implementation.
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/emojicode/bogo_sort.emojic
Labels: Hacktoberfest, Implementation

#488 fixed formatting issues in nim implementation of monte carlo
  contents/monte_carlo_integration/code/nim/monte_carlo.nim
Labels: Hacktoberfest, Implementation Edit

#459 Add Graham Scan in Java
  contents/graham_scan/code/java/GrahamScan.java
  contents/graham_scan/graham_scan.md
Labels: Hacktoberfest, Implementation

#404 add the jarvis march in go
  contents/jarvis_march/code/golang/jarvis.go
  contents/jarvis_march/jarvis_march.md
Labels: Hacktoberfest, Implementation

#484 Add verlet integration in golang
  contents/verlet_integration/code/golang/verlet.go
  contents/verlet_integration/verlet_integration.md
Labels: Hacktoberfest, Implementation

#485 add the forward euler method in golang
  contents/forward_euler_method/code/golang/euler.go
  contents/forward_euler_method/forward_euler_method.md
Labels: Hacktoberfest, Implementation

#490 change the name golang to go
  contents/bubble_sort/bubble_sort.md
  contents/euclidean_algorithm/euclidean_algorithm.md
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/tree_traversal/tree_traversal.md
Labels: Hacktoberfest

#468 Add Euclidean Algorithm in Emojicode.
  contents/euclidean_algorithm/code/emojicode/euclidean_algorithm.emojic
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#464 Added gaussian elimination in js
  contents/gaussian_elimination/code/javascript/gaussian_elimination.js
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Hacktoberfest, Implementation

#438 Add gaussian elimination in Java
  contents/gaussian_elimination/code/java/GaussianElimination.java
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Hacktoberfest, Implementation

#482 Verlet integration in ruby
  contents/verlet_integration/code/ruby/verlet.rb
  contents/verlet_integration/verlet_integration.md
Labels: Hacktoberfest, Implementation

#461 Add Bogosort in Racket
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/racket/bogo_sort.rkt
Labels: Hacktoberfest, Implementation

#402 add the graham scan in go
  contents/graham_scan/code/golang/graham.go
  contents/graham_scan/graham_scan.md
Labels: Hacktoberfest, Implementation

#403 add huffman encoding in go
  contents/huffman_encoding/code/golang/huffman.go
  contents/huffman_encoding/huffman_encoding.md
Labels: Hacktoberfest, Implementation

#354 Jarvis March Implementation in Java
  CONTRIBUTORS.md
  contents/jarvis_march/code/java/JarvisMarch.java
  contents/jarvis_march/jarvis_march.md
Labels: Implementation

#498 Editorconfig updates
  .editorconfig
Labels: General, Hacktoberfest

#497 Euclid algorithm in bash
  book.json
  contents/euclidean_algorithm/code/bash/euclid.bash
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#500 Small change to utility.h
  contents/tree_traversal/code/c/utility.h
Labels: Hacktoberfest, Implementation Edit

#495 Fixing Julia for Thomas algorithm
  contents/thomas_algorithm/code/julia/thomas.jl
Labels: Hacktoberfest, Implementation Edit

#496 Clean up Java implementation of Thomas Algorithm
  contents/thomas_algorithm/code/java/Thomas.java
  contents/thomas_algorithm/code/java/thomas.java
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation Edit

#508 Fix the x64 assembly version of Huffman encoding
  contents/huffman_encoding/code/asm-x64/huffman.s
Labels: Hacktoberfest, Implementation Edit

#513 Fix book.json
  book.json
Labels: Hacktoberfest

#506 Cleanup files
  tools/cleanup/clean_book_json.py
  tools/cleanup/clean_editorconfig.py
Labels: General, Hacktoberfest

#503 Forward euler in x86_64
  contents/forward_euler_method/code/asm-x64/euler.s
  contents/forward_euler_method/forward_euler_method.md
Labels: Hacktoberfest, Implementation

#367 Adding Euclidean Algorithms in X86-64 Assembly
  contents/euclidean_algorithm/code/asm-x64/euclidean_example.s
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation

#502 Monte carlo in X86_64
  contents/monte_carlo_integration/code/asm-x64/monte_carlo.s
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#509 Added bubblesort in bash
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/bash/bubble_sort.bash
Labels: Hacktoberfest, Implementation

#501 Small change to monte_carlo.c
  contents/monte_carlo_integration/code/c/monte_carlo.c
Labels: Hacktoberfest, Implementation Edit

#504 Tree traversal in X86_64
  contents/tree_traversal/code/asm-x64/tree_traversal.s
  contents/tree_traversal/tree_traversal.md
Labels: Hacktoberfest, Implementation

#446 Lisp jarvis march
  contents/jarvis_march/code/lisp/jarvis-march.lisp
  contents/jarvis_march/jarvis_march.md
Labels: Hacktoberfest, Implementation

#514 Lisp Monte Carlo
  contents/monte_carlo_integration/code/lisp/monte-carlo.lisp
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#434 Add Monte Carlo implementation in Factor
  contents/monte_carlo_integration/code/factor/monte_carlo.factor
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Hacktoberfest, Implementation

#512 Lisp bogo sort
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/lisp/bogo-sort.lisp
Labels: Hacktoberfest, Implementation

#505 Verlet in X86_64
  contents/verlet_integration/code/asm-x64/verlet.s
  contents/verlet_integration/verlet_integration.md
Labels: Hacktoberfest, Implementation

#517 Bogo Sort in X86_64
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/asm-x64/bogo_sort.s
Labels: Hacktoberfest, Implementation

#523 Added crystal to .editorconfig
  .editorconfig
Labels: Hacktoberfest

#527 Fixing X86_64 formating in the book
  contents/bogo_sort/bogo_sort.md
  contents/bubble_sort/bubble_sort.md
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Chapter Edit, Hacktoberfest

#365 Add bogo sort in Golang
  CONTRIBUTORS.md
  contents/bogo_sort/code/go/main.go
Labels: Implementation

#526 Added exclamation marks to mutating julia functions
  contents/bogo_sort/code/julia/bogo.jl
  contents/bubble_sort/code/julia/bubble.jl
  contents/gaussian_elimination/code/julia/gaussian_elimination.jl
  contents/graham_scan/code/julia/graham.jl
  contents/huffman_encoding/code/julia/huffman.jl
  contents/split-operator_method/code/julia/split_op.jl
Labels: Hacktoberfest, Implementation Edit

#522 Implemented Thomas Algorithm in Lua
  CONTRIBUTORS.md
  contents/thomas_algorithm/code/lua/thomas.lua
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Hacktoberfest, Implementation

#521 updating how_to_contribute.md and removing version control chapter.
  SUMMARY.md
  contents/git_and_version_control/git_and_version_control.md
  contents/git_and_version_control/res/clone.png
  contents/git_and_version_control/res/fork.png
  contents/how_to_contribute/how_to_contribute.md
Labels: Chapter Edit, General, Hacktoberfest

#420 Added C++ lang implementation of the split operator
  contents/split-operator_method/code/c++/split_op.cpp
  contents/split-operator_method/split-operator_method.md
Labels: Hacktoberfest, Implementation

#476 C++ quantum systems' energy calculations implementation
  contents/quantum_systems/code/c++/energy.cpp
  contents/quantum_systems/quantum_systems.md
Labels: Hacktoberfest, Implementation

#516 Added bogo sort in bash
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/bash/bogo_sort.bash
Labels: Hacktoberfest, Implementation

#467 Huffman encoding implementation in scala
  contents/huffman_encoding/code/scala/huffman_encoding.scala
  contents/huffman_encoding/huffman_encoding.md
Labels: Hacktoberfest, Implementation

#529 Implemented Thomas Algorithm in Crystal
  contents/thomas_algorithm/code/crystal/thomas.cr
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Hacktoberfest, Implementation

#418 Forward Euler in JavaScript
  contents/forward_euler_method/code/javascript/euler.js
  contents/forward_euler_method/forward_euler_method.md
Labels: Hacktoberfest, Implementation

#515 PHP unify code style
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/php/bogo_sort.php
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/php/bubble_sort.php
  contents/tree_traversal/code/php/tree_traversal.php
  contents/tree_traversal/tree_traversal.md
Labels: Hacktoberfest, Implementation Edit

#518 Add Java implementation of Forward Euler
  contents/forward_euler_method/code/java/ForwardEuler.java
  contents/forward_euler_method/forward_euler_method.md
Labels: Hacktoberfest, Implementation

#536 Add Bogo sort in R
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/r/bogo_sort.r
Labels: Hacktoberfest, Implementation

#397 Haskell: added DFT and re-wrote FFT
  contents/cooley_tukey/code/haskell/fft.hs
  contents/cooley_tukey/cooley_tukey.md
Labels: Hacktoberfest, Implementation Edit
