Repository algorithm-archivists/algorithm-archive, pull requests merged in 2018-12, with the labels that each got.

#544 Gaussian elimination revisions
  contents/gaussian_elimination/code/java/GaussianElimination.java
  contents/gaussian_elimination/code/julia/gaussian_elimination.jl
  contents/gaussian_elimination/code/python/gaussian_elimination.py
  contents/gaussian_elimination/code/rust/gaussian_elimination.rs
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Chapter Edit, Implementation Edit

#554 Adding videos to chapters
  contents/bitlogic/bitlogic.md
  contents/euclidean_algorithm/euclidean_algorithm.md
  contents/forward_euler_method/forward_euler_method.md
  contents/gaussian_elimination/gaussian_elimination.md
  contents/huffman_encoding/huffman_encoding.md
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/split-operator_method/split-operator_method.md
  contents/stable_marriage_problem/stable_marriage_problem.md
  contents/tree_traversal/tree_traversal.md
  contents/verlet_integration/verlet_integration.md
Labels: Chapter Edit, General

#556 adding go implementation to bogo_sort.md
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/go/bogo_sort.go
Labels: Small Changes

#547 Added Bubblesort in Chip-8 assembly
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/chip8/bubblesort.c8
Labels: Implementation

#561 Add the Prism Syntax Highlighting Plugin
  book.json
  contents/bogo_sort/bogo_sort.md
  contents/bubble_sort/bubble_sort.md
  contents/convolutions/convolutions.md
  contents/cooley_tukey/cooley_tukey.md
  contents/forward_euler_method/forward_euler_method.md
  contents/gaussian_elimination/gaussian_elimination.md
  contents/graham_scan/graham_scan.md
  contents/huffman_encoding/huffman_encoding.md
  contents/jarvis_march/jarvis_march.md
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/quantum_systems/quantum_systems.md
  contents/split-operator_method/split-operator_method.md
  contents/stable_marriage_problem/stable_marriage_problem.md
  contents/thomas_algorithm/thomas_algorithm.md
  contents/tree_traversal/tree_traversal.md
  contents/verlet_integration/verlet_integration.md
Labels: General

#562 Make Python Jarvis March conform to PEP8, take 2
  contents/jarvis_march/code/python/jarvisMarch.py
  contents/jarvis_march/code/python/jarvis_march.py
  contents/jarvis_march/jarvis_march.md
Labels: Implementation Edit

#566 removing convolutions chapter while reworking it
  SUMMARY.md
Labels: Chapter Edit

#542 Adding FFT in X86_64
  contents/cooley_tukey/code/asm-x64/fft.s
  contents/cooley_tukey/cooley_tukey.md
Labels: Implementation
