Repository algorithm-archivists/algorithm-archive, pull requests merged in 2019-03, with the labels that each got.

#593 fixing typo in step 2 of Gaussian Elimination
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Chapter Edit

#569 adding some templates to be modified in review
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CHAPTER_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE/CHAPTER_SUBMISSION_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/CODE_SUBMISSION_TEMPLATE.md
Labels: General

#596 An implementation of Euclidean Algorithm in D
  contents/euclidean_algorithm/code/d/euclidean_algorithm.d
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation
