Repository algorithm-archivists/algorithm-archive, pull requests merged in 2019-10, with the labels that each got.

#608 Verlet implementation in Common Lisp
  contents/verlet_integration/code/clisp/verlet.lisp
  contents/verlet_integration/verlet_integration.md
Labels: Implementation

#639 Kotlin capitalization fix
  book.json
Labels: Small Changes

#642 Update Graham Scan in C to use points from Julia implementation
  contents/graham_scan/code/c/graham.c
Labels: Implementation Edit

#559 Gauss Jordan elimination in rust
  contents/gaussian_elimination/code/rust/gaussian_elimination.rs
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Implementation Edit

#643 Update Graham Scan in JavaScript to use points from Julia implementation
  contents/graham_scan/code/javascript/graham-scan.js
Labels: Hacktoberfest, Implementation Edit

#651 implemented bubblesort in coffeescript and added it to book.json
  .editorconfig
  book.json
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/coffeescript/bubblesort.coffee
Labels: Hacktoberfest, Implementation

#633 V forward euler
  .editorconfig
  book.json
  contents/forward_euler_method/code/v/euler.v
  contents/forward_euler_method/forward_euler_method.md
Labels: Hacktoberfest, Implementation

#632 jarVis march
  contents/jarvis_march/code/v/jarvis.v
  contents/jarvis_march/jarvis_march.md
Labels: Hacktoberfest, Implementation

#634 V thomas
  contents/thomas_algorithm/code/v/thomas.v
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Hacktoberfest, Implementation

#631 bubblesort in v
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/v/bubble_sort.v
Labels: Hacktoberfest, Implementation

#644 Make Graham Scan in Python PEP8 compliant
  contents/graham_scan/code/python/grahamScan.py
  contents/graham_scan/code/python/graham_scan.py
  contents/graham_scan/graham_scan.md
Labels: Hacktoberfest, Implementation Edit
