Repository algorithm-archivists/algorithm-archive, pull requests merged in 2019-12, with the labels that each got.

#626 Add Euclidean Algorithm in PowerShell
  .editorconfig
  book.json
  contents/euclidean_algorithm/code/powershell/euclidean_algorithm.ps1
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Hacktoberfest, Implementation

#622 Plotting chapter addition
  .gitignore
  SUMMARY.md
  contents/plotting/code/gnuplot/example_tex.gp
  contents/plotting/code/gnuplot/latex_import.tex
  contents/plotting/code/gnuplot/sine.gp
  contents/plotting/code/gnuplot/sine_to_file.gp
  contents/plotting/data/1d_sample_data.dat
  contents/plotting/data/1d_sample_low_res.dat
  contents/plotting/data/2d_sample_data.dat
  contents/plotting/data/2d_sample_low_res.dat
  contents/plotting/data/scatterplot_data.dat
  contents/plotting/plotting.md
  contents/plotting/res/gnuplot/1d_sample.png
  contents/plotting/res/gnuplot/2d_sample.png
  contents/plotting/res/gnuplot/2d_sample_cb.png
  contents/plotting/res/gnuplot/exp.png
  contents/plotting/res/gnuplot/explog.png
  contents/plotting/res/gnuplot/exponential_tex.png
  contents/plotting/res/gnuplot/scatterplot.png
  contents/plotting/res/gnuplot/sincos.png
  contents/plotting/res/gnuplot/sincos_customtics.png
  contents/plotting/res/gnuplot/sincos_label.png
  contents/plotting/res/gnuplot/sincos_log.png
  contents/plotting/res/gnuplot/sincos_lt.png
  contents/plotting/res/gnuplot/sincos_movekey.png
  contents/plotting/res/gnuplot/sincos_movekey2.png
  contents/plotting/res/gnuplot/sincos_nokey.png
  contents/plotting/res/gnuplot/sincos_notics.png
  contents/plotting/res/gnuplot/sincos_range.png
  contents/plotting/res/gnuplot/sincos_square.png
  contents/plotting/res/gnuplot/sincos_title.png
  contents/plotting/res/gnuplot/sine.png
  contents/plotting/res/gnuplot/test.png
  contents/plotting/res/sincos_lt.png
  literature.bib
Labels: Chapter

#661 Fixed Huffman Encoding edge case failure in C.
  contents/huffman_encoding/code/c/huffman.c
Labels: Implementation Edit
