Repository algorithm-archivists/algorithm-archive, pull requests merged in 2019-01, with the labels that each got.

#571 C adding FFT test
  contents/cooley_tukey/code/c/fft.c
  contents/cooley_tukey/cooley_tukey.md
Labels: Implementation Edit

#555 "Gaussian Elimination" Implementation in C++
  contents/gaussian_elimination/code/c++/gaussian_elimination.cpp
  contents/gaussian_elimination/gaussian_elimination.md
Labels: Implementation

#572 Format Rust code using rustfmt
  contents/bogo_sort/code/rust/bogosort.rs
  contents/bubble_sort/code/rust/bubble_sort.rs
  contents/euclidean_algorithm/code/rust/euclidean_example.rs
  contents/monte_carlo_integration/code/rust/monte_carlo.rs
  contents/tree_traversal/code/rust/tree.rs
  contents/verlet_integration/code/rust/verlet.rs
Labels: Implementation Edit

#573 Use pattern matching in tree traversal (Rust)
  contents/tree_traversal/code/rust/tree.rs
  contents/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#574 Make README more readable.
  README.md
Labels: Chapter Edit

#578 Minor edit to the Bit Logic page
  contents/bitlogic/bitlogic.md
Labels: Chapter Edit

#577 Java filename changes for Verlet / bogosort / bubblesort
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/java/Bogo.java
  contents/bubble_sort/bubble_sort.md
  contents/bubble_sort/code/java/Bubble.java
  contents/monte_carlo_integration/code/java/MonteCarlo.java
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/verlet_integration/code/java/Verlet.java
  contents/verlet_integration/code/java/VerletValues.java
  contents/verlet_integration/verlet_integration.md
Labels: Implementation Edit
