Repository algorithm-archivists/algorithm-archive, pull requests merged in 2020-06, with the labels that each got.

#707 Update C Jarvis March to use points from Graham Scan
  contents/jarvis_march/code/c/jarvis_march.c
Labels: Implementation Edit

#706 Update C++ Jarvis March to use points from Graham Scan
  contents/jarvis_march/code/c++/jarvis_march.cpp
Labels: Implementation Edit

#714 IFS in C
  contents/IFS/IFS.md
  contents/IFS/code/c/IFS.c
Labels: Implementation

#716 Domain coloring
  SUMMARY.md
  contents/domain_coloring/code/gnuplot/domain_coloring.gp
  contents/domain_coloring/domain_coloring.md
  contents/domain_coloring/domain_coloring.md.bak
  contents/domain_coloring/res/absz.png
  contents/domain_coloring/res/hsv.png
  contents/domain_coloring/res/hsv2.png
  contents/domain_coloring/res/hsv3.png
  contents/domain_coloring/res/hsv4.png
  contents/domain_coloring/res/hsv5.png
  contents/domain_coloring/res/rgb1.png
  contents/domain_coloring/res/rgb2.png
  contents/domain_coloring/res/shade.png
  contents/domain_coloring/res/z2.png
  literature.bib
Labels: Chapter
