Repository algorithm-archivists/algorithm-archive, pull requests merged in 2020-04, with the labels that each got.

#673 Easter algorithm chapter
  SUMMARY.md
  contents/computus/code/julia/gauss_easter.jl
  contents/computus/computus.md
  contents/computus/res/orbit.png
  contents/computus/res/orbit.svg
  contents/computus/res/servois_1800.png
  contents/computus/res/servois_2000.png
  contents/computus/res/synodic_half_year.png
  literature.bib
Labels: Chapter

#674 Small changes to computus
  contents/computus/computus.md
Labels: Chapter Edit

#618 Update images of Scratch Implemantation to Scratch3
  contents/thomas_algorithm/code/scratch/thomas.svg
  contents/thomas_algorithm/code/scratch/thomas.txt
  contents/tree_traversal/code/scratch/all.svg
  contents/tree_traversal/code/scratch/bfs.svg
  contents/tree_traversal/code/scratch/dfs-from.svg
  contents/tree_traversal/code/scratch/dfs-in.svg
  contents/tree_traversal/code/scratch/dfs-post.svg
  contents/tree_traversal/code/scratch/dfs-pre.svg
  contents/tree_traversal/code/scratch/dfs-stack.svg
  contents/tree_traversal/code/scratch/dfs.svg
  contents/tree_traversal/code/scratch/struct.svg
  contents/tree_traversal/code/scratch/tree_traversal.txt
  contents/tree_traversal/tree_traversal.md
Labels: Implementation Edit

#680 modifying gauss's easter algorithm to always output strings
  contents/computus/code/crystal/gauss_easter.cr
  contents/computus/code/julia/gauss_easter.jl
  contents/computus/code/python/gauss_easter.py
Labels: Implementation Edit, Small Changes

#627 Unified Lua code style across pages
  contents/bogo_sort/bogo_sort.md
  contents/bogo_sort/code/lua/bogosort.lua
  contents/bubble_sort/code/lua/bubble_sort.lua
  contents/euclidean_algorithm/code/lua/euclidean.lua
  contents/huffman_encoding/code/lua/huffman.lua
  contents/monte_carlo_integration/code/lua/monte_carlo.lua
  contents/monte_carlo_integration/monte_carlo_integration.md
  contents/thomas_algorithm/code/lua/thomas.lua
Labels: Hacktoberfest, Implementation Edit

#619 Monte Carlo Scratch Implementation
  contents/monte_carlo_integration/code/scratch/Algorithm.svg
  contents/monte_carlo_integration/code/scratch/InCircle.svg
  contents/monte_carlo_integration/code/scratch/monte_carlo.txt
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation
