Repository algorithm-archivists/algorithm-archive, pull requests merged in 2020-11, with the labels that each got.

#779 Add Scheme alongside Racket in EditorConfig
  .editorconfig
Labels: General, Hacktoberfest, hacktoberfest-accepted

#777 Added CSS for printing pages
  styles/website.css
Labels: GitBook, Hacktoberfest, hacktoberfest-accepted

#784 Make Euclid's algorithm in Nim more idiomatic
  contents/euclidean_algorithm/code/nim/euclid_algorithm.nim
Labels: Hacktoberfest, Implementation Edit, hacktoberfest-accepted

#782 Make Verlet integration in Nim more idiomatic
  contents/verlet_integration/code/nim/verlet.nim
Labels: Hacktoberfest, Implementation Edit, hacktoberfest-accepted

#783 Make Bogosort in Nim more idiomatic
  contents/bogo_sort/code/nim/bogo_sort.nim
Labels: Hacktoberfest, Implementation Edit, hacktoberfest-accepted
