Repository algorithm-archivists/algorithm-archive, pull requests merged in 2020-05, with the labels that each got.

#683 Thomas alg in Javascript fixup
  contents/thomas_algorithm/code/javascript/thomas.js
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation, Implementation Edit

#697 Adding computus in C
  contents/computus/code/c/gauss_easter.c
  contents/computus/computus.md
Labels: Implementation

#696 adding matlab implementation to monte carlo integration
  contents/monte_carlo_integration/code/matlab/monte.m
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation

#703 Add computus in C++
  contents/computus/code/c++/gauss_easter.cpp
  contents/computus/computus.md
Labels: Implementation

#605 Graham scan implementation in Common Lisp
  contents/graham_scan/code/clisp/graham-scan.lisp
  contents/graham_scan/graham_scan.md
Labels: Implementation

#684 Computus Powershell Implementation
  contents/computus/code/powershell/gauss_easter.ps1
  contents/computus/computus.md
Labels: Implementation

#710 fixing julia function to output pi estimate
  contents/monte_carlo_integration/code/julia/monte_carlo.jl
Labels: Implementation Edit

#695 Add Computus in Rust
  contents/computus/code/rust/gauss_easter.rs
  contents/computus/computus.md
Labels: Implementation

#693 Add Thomas Algorithm in Rust
  contents/thomas_algorithm/code/rust/thomas.rs
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation

#607 Forward euler implementation in Common Lisp
  contents/forward_euler_method/code/clisp/euler.lisp
  contents/forward_euler_method/forward_euler_method.md
Labels: Implementation

#690 Tree traversal in MATLAB
  contents/tree_traversal/code/matlab/tree.m
  contents/tree_traversal/tree_traversal.md
Labels: Implementation

#700 Add IFS in python
  CONTRIBUTORS.md
  contents/IFS/IFS.md
  contents/IFS/code/python/IFS.py
Labels: Implementation
