Repository algorithm-archivists/algorithm-archive, pull requests merged in 2020-07, with the labels that each got.

#725 Added Graham scan in Coconut
  contents/graham_scan/code/coconut/graham_scan.coco
  contents/graham_scan/graham_scan.md
Labels: Implementation

#721 Euclidean algorithm in coconut
  book.json
  contents/euclidean_algorithm/code/coconut/euclidean.coco
  contents/euclidean_algorithm/euclidean_algorithm.md
Labels: Implementation

#688 Add FFT in Rust
  contents/cooley_tukey/code/rust/fft.rs
  contents/cooley_tukey/cooley_tukey.md
Labels: Implementation

#623 Tree Traversal in Common Lisp
  contents/tree_traversal/code/clisp/tree-traversal.lisp
  contents/tree_traversal/tree_traversal.md
Labels: Implementation

#604 Thomas algorithm implementation in Common Lisp
  contents/thomas_algorithm/code/clisp/thomas.lisp
  contents/thomas_algorithm/thomas_algorithm.md
Labels: Implementation

#720 Use HonKit instead of GitBook
  .github/PULL_REQUEST_TEMPLATE/CHAPTER_SUBMISSION_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/CODE_SUBMISSION_TEMPLATE.md
  .travis.yml
  book.json
  contents/how_to_contribute/how_to_contribute.md
  package.json
  update_site.sh
Labels: GitBook

#728 Update Travis for HonKit build
  .travis.yml
  tools/deploy/update_site_travis.bash
Labels: GitBook, Problem

#687 Improved stable marriage problem Python implementation
  CONTRIBUTORS.md
  contents/stable_marriage_problem/code/python/stable_marriage.py
Labels: Implementation Edit

#723 Rust implementation of the jarvis march algorithm
  CONTRIBUTORS.md
  contents/jarvis_march/code/rust/jarvis_march.rs
  contents/jarvis_march/jarvis_march.md
Labels: Implementation

#679 [Haskell] Computus
  contents/computus/code/haskell/gauss_easter.hs
  contents/computus/computus.md
Labels: Implementation

#727 IFS in coconut
  .gitignore
  contents/IFS/IFS.md
  contents/IFS/code/coconut/IFS.coco
Labels: Implementation

#731 Added tree traversal in Coconut
  contents/tree_traversal/code/coconut/tree_traversal.coco
  contents/tree_traversal/tree_traversal.md
Labels: Implementation

#724 Computus Common Lisp Implementation
  contents/computus/code/clisp/gauss-easter.lisp
  contents/computus/computus.md
Labels: Implementation

#733 Added Monte Carlo integration in Coconut
  contents/monte_carlo_integration/code/coconut/monte_carlo.coco
  contents/monte_carlo_integration/monte_carlo_integration.md
Labels: Implementation
