Repository algorithm-archivists/algorithm-archive, pull requests merged in 2021-08, with the labels that each got.

#829 Fix typo in barnsley/julia
  contents/barnsley/code/julia/barnsley.jl
Labels: Implementation Edit

#775 feat(ts): stack and queue implementation
  contents/stacks_and_queues/code/typescript/queue.ts
  contents/stacks_and_queues/code/typescript/stack.ts
Labels: Implementation, Hacktoberfest, hacktoberfest-accepted

#819 Convolutions of Images 2d Python implementation
  CONTRIBUTORS.md
  contents/convolutions/2d/2d.md
  contents/convolutions/code/python/2d_convolution.py
Labels: Implementation

#830 Add Barnsley Farn java implementation
  contents/barnsley/barnsley.md
  contents/barnsley/code/java/Barnsley.java
Labels: Implementation

#832 Add Barnsley Fern in C
  CONTRIBUTORS.md
  contents/barnsley/barnsley.md
  contents/barnsley/code/c/barnsley.c
Labels: Implementation

#842 Tree traversal: Change front and top to first
  contents/tree_traversal/code/julia/Tree.jl
Labels: Implementation Edit

#839 adding stack and queue code infrastructure
  book.json
  contents/stacks_and_queues/stacks_and_queues.md
Labels: Chapter Edit

#834 Add approximate counting C++ sample code
  contents/approximate_counting/approximate_counting.md
  contents/approximate_counting/code/c++/approximate_counting.cpp
Labels: Implementation

#835 C++ sample code for The Barnsley Fern
  contents/barnsley/barnsley.md
  contents/barnsley/code/c++/barnsley.cpp
Labels: Implementation

#840 small typos in julia code that could be a problem in other languages. Added abs and fixed <=
  contents/approximate_counting/code/julia/approximate_counting.jl
Labels: Implementation Edit

#807 Add Computus in Javascript and Typescript
  CONTRIBUTORS.md
  book.json
  contents/computus/code/dart/gauss_easter.dart
  contents/computus/code/javascript/gauss_easter.js
  contents/computus/code/typescript/gauss_easter.ts
  contents/computus/computus.md
Labels: Implementation

#705 Update C# Jarvis March to use points from Graham Scan
  contents/jarvis_march/code/csharp/Program.cs
Labels: Implementation Edit, lang: c#

#704 [Haskell] IFS
  contents/IFS/IFS.md
  contents/IFS/code/haskell/IFS.hs
Labels: Implementation, lang: haskell

#849 General implementation cleanup
  contents/huffman_encoding/code/java/huffman.java
  contents/monte_carlo_integration/code/c++/monte_carlo.cpp
  contents/tree_traversal/code/java/MainClass.java
  contents/tree_traversal/code/java/Tree.java
  contents/tree_traversal/tree_traversal.md
  contents/verlet_integration/code/java/Verlet.java
  contents/verlet_integration/code/java/VerletValues.java
  contents/verlet_integration/verlet_integration.md
Labels: lang: c++, lang: java, lang: cpp
