Repository algorithm-archivists/algorithm-archive, pull requests merged in 2022-01, with the labels that each got.

#936 Stack queue in cpp
  contents/stacks_and_queues/code/cpp/queue.cpp
  contents/stacks_and_queues/code/cpp/stack.cpp
  contents/stacks_and_queues/stacks_and_queues.md
Labels: Implementation, lang: c++

#964 Implement Graham Scan in Rust
  CONTRIBUTORS.md
  contents/graham_scan/code/rust/graham_scan.rs
  contents/graham_scan/graham_scan.md
Labels: Implementation, lang: rust

#985 Solved formatting problems
  contents/IFS/IFS.md
  contents/stacks_and_queues/stacks_and_queues.md
Labels: Problem, Chapter Edit, Small Changes, GitBook

#984 Added Kotlin compilation
  SConstruct
  builders/kotlin.py
  sconscripts/kotlin_SConscript
Labels: SCons

#932 Fix warnings and remove VLA on C++ Thomas algorithm
  contents/thomas_algorithm/code/cpp/thomas.cpp
Labels: Implementation Edit, lang: c++

#987 Eliminating C/C++ implicit conversions
  SConstruct
  contents/IFS/code/c/IFS.c
  contents/approximate_counting/code/c/approximate_counting.c
  contents/cooley_tukey/code/c/fft.c
  contents/cooley_tukey/code/cpp/fft.cpp
  contents/forward_euler_method/code/c/euler.c
  contents/forward_euler_method/code/cpp/euler.cpp
  contents/gaussian_elimination/code/cpp/gaussian_elimination.cpp
  contents/graham_scan/code/c/graham.c
  contents/huffman_encoding/code/c/huffman.c
  contents/monte_carlo_integration/code/c/monte_carlo.c
  contents/split-operator_method/code/c/split_op.c
  contents/split-operator_method/code/cpp/split_op.cpp
  contents/stable_marriage_problem/code/c/stable_marriage.c
  contents/thomas_algorithm/code/c/thomas.c
Labels: Implementation Edit, lang: c++, lang: c, SCons

#988 Small revisions to crypto chapter
  SUMMARY.md
  contents/cryptography/cryptography.md
  contents/cryptography/res/table.jl
  literature.bib
  redirects.json
Labels: Chapter
